#!/usr/bin/env python3
"""Generate base14_font_data.cpp from third_party/fonts/*.pfb.

Community-extensions ship a single .duckdb_extension binary with no companion
data files, so base-14 substitute fonts must be compiled into the extension
and extracted to a temp directory at runtime for poppler's path-based
GlobalParams::setupBaseFonts / addFontFile APIs.

Poppler's no-fontconfig path (vcpkg default-features: false) looks for the
legacy Ghostscript URW filenames in setupBaseFonts():

  Helvetica*  → n01900{3,4,23,24}l.pfb
  Times*      → n02100{3,4,23,24}l.pfb
  Courier*    → n02200{3,4,23,24}l.pfb
  Symbol      → s050000l.pfb
  ZapfDingbats→ d050000l.pfb

We ship Artifex URW Type1 (.t1) bytes renamed to those .pfb names. OpenType
OTFs + addFontFile alone are not enough on community Linux CI (no fontconfig).

Usage:
  python3 scripts/embed_base14_fonts.py third_party/fonts path/to/base14_font_data.cpp
"""

from __future__ import annotations

import sys
from pathlib import Path

# (PDF base-14 name, poppler/setupBaseFonts filename on disk)
BASE14 = [
    ("Helvetica", "n019003l.pfb"),
    ("Helvetica-Bold", "n019004l.pfb"),
    ("Helvetica-Oblique", "n019023l.pfb"),
    ("Helvetica-BoldOblique", "n019024l.pfb"),
    ("Times-Roman", "n021003l.pfb"),
    ("Times-Bold", "n021004l.pfb"),
    ("Times-Italic", "n021023l.pfb"),
    ("Times-BoldItalic", "n021024l.pfb"),
    ("Courier", "n022003l.pfb"),
    ("Courier-Bold", "n022004l.pfb"),
    ("Courier-Oblique", "n022023l.pfb"),
    ("Courier-BoldOblique", "n022024l.pfb"),
    ("Symbol", "s050000l.pfb"),
    ("ZapfDingbats", "d050000l.pfb"),
]


def c_ident(filename: str) -> str:
    return "kFont_" + filename.replace("-", "_").replace(".", "_")


def emit_array(out, name: str, data: bytes) -> None:
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        line = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + 16 < len(data):
            out.write(f"\t{line},\n")
        else:
            out.write(f"\t{line}\n")
    out.write("};\n")
    out.write(f"static const size_t {name}_len = {len(data)};\n\n")


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    font_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    if not font_dir.is_dir():
        print(f"font dir not found: {font_dir}", file=sys.stderr)
        return 1

    blobs = []
    for base14_name, filename in BASE14:
        path = font_dir / filename
        if not path.is_file():
            print(f"missing font file: {path}", file=sys.stderr)
            return 1
        blobs.append((base14_name, filename, path.read_bytes()))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("// AUTO-GENERATED by scripts/embed_base14_fonts.py — do not edit.\n")
        out.write("// Source fonts: third_party/fonts/ (URW++ Type1 as poppler PFB names).\n\n")
        out.write('#include "base14_fonts.hpp"\n\n')
        out.write('#include "GlobalParams.h"\n\n')
        out.write("#include <cerrno>\n")
        out.write("#include <cstdio>\n")
        out.write("#include <cstdlib>\n")
        out.write("#include <cstring>\n")
        out.write("#include <fstream>\n")
        out.write("#include <string>\n\n")
        out.write("#ifdef _WIN32\n")
        out.write("#include <direct.h>\n")
        out.write("#include <io.h>\n")
        out.write("#else\n")
        out.write("#include <sys/stat.h>\n")
        out.write("#include <sys/types.h>\n")
        out.write("#include <unistd.h>\n")
        out.write("#endif\n\n")

        for base14_name, filename, data in blobs:
            emit_array(out, c_ident(filename), data)

        out.write("struct Base14FontBlob {\n")
        out.write("\tconst char *base14_name;\n")
        out.write("\tconst char *filename;\n")
        out.write("\tconst unsigned char *data;\n")
        out.write("\tsize_t size;\n")
        out.write("};\n\n")
        out.write("static const Base14FontBlob kBase14Fonts[] = {\n")
        for base14_name, filename, _data in blobs:
            ident = c_ident(filename)
            out.write(f'\t{{"{base14_name}", "{filename}", {ident}, {ident}_len}},\n')
        out.write("};\n")
        out.write(f"static const size_t kBase14FontCount = {len(blobs)};\n\n")

        out.write(r'''
static std::string Base14TempRoot() {
#ifdef _WIN32
const char *candidates[] = {std::getenv("TEMP"), std::getenv("TMP"), "."};
#else
const char *candidates[] = {std::getenv("TMPDIR"), std::getenv("TMP"), "/tmp"};
#endif
for (const char *c : candidates) {
if (c && *c) {
std::string dir(c);
while (dir.size() > 1 && (dir.back() == '/' || dir.back() == '\\')) {
dir.pop_back();
}
return dir;
}
}
return ".";
}

static bool EnsureDir(const std::string &path) {
#ifdef _WIN32
if (_mkdir(path.c_str()) == 0) {
return true;
}
return errno == EEXIST;
#else
if (mkdir(path.c_str(), 0755) == 0) {
return true;
}
return errno == EEXIST;
#endif
}

static bool WriteFileIfNeeded(const std::string &path, const unsigned char *data, size_t size) {
// Reuse an existing file only when the size matches (cheap integrity check).
{
std::ifstream in(path, std::ios::binary | std::ios::ate);
if (in && static_cast<size_t>(in.tellg()) == size) {
return true;
}
}
const std::string tmp = path + ".tmp";
{
std::ofstream out(tmp, std::ios::binary | std::ios::trunc);
if (!out) {
return false;
}
out.write(reinterpret_cast<const char *>(data), static_cast<std::streamsize>(size));
if (!out) {
return false;
}
}
#ifdef _WIN32
_unlink(path.c_str());
if (rename(tmp.c_str(), path.c_str()) != 0) {
_unlink(tmp.c_str());
return false;
}
#else
if (rename(tmp.c_str(), path.c_str()) != 0) {
std::remove(tmp.c_str());
return false;
}
#endif
return true;
}

namespace duckdb {

// Extract bundled URW Type1 base-14 fonts to a process temp dir and register
// them with poppler so display-font resolution works without fontconfig.
// Safe to call under PopplerMutex; idempotent once all files land.
void EnsurePdfBase14Fonts() {
static bool done = false;
if (done) {
return;
}
// poppler creates globalParams on first document open; without it we cannot
// register fonts yet. Caller retries on the next render.
if (!globalParams) {
return;
}

#ifdef _WIN32
const char sep = '\\';
#else
const char sep = '/';
#endif
// Bump dir suffix when font payload changes so stale bad trees are not reused.
// v3 = real binary PFB (0x80 0x01 segments), not PFA text misnamed as .pfb.
const std::string dir = Base14TempRoot() + sep + "duckdb_pdf_base14_fonts_v4_t1binary";
if (!EnsureDir(dir)) {
// Non-fatal: leave done=false so a later call can retry; poppler may
// still find system fonts, and the fail-loudly path remains as a last resort.
return;
}

bool all_ok = true;
for (size_t i = 0; i < kBase14FontCount; i++) {
const Base14FontBlob &blob = kBase14Fonts[i];
const std::string path = dir + sep + blob.filename;
if (!WriteFileIfNeeded(path, blob.data, blob.size)) {
all_ok = false;
continue;
}
// External-font map (findFontFile) — covers callers that do not go through
// the base-14 displayFontTab path.
globalParams->addFontFile(std::string(blob.base14_name), path);
}
// Critical for vcpkg poppler with fontconfig OFF: walk displayFontTab and
// resolve Helvetica/etc. via the legacy n0*.pfb filenames we just wrote.
// Files must be real binary PFB (FreeType rejects mislabeled PFA on some builds).
globalParams->setupBaseFonts(dir.c_str());

// When poppler is built WITH fontconfig (community may enable it), point it at
// our temp tree so system fontconfig emptiness does not blank-render pages.
{
const std::string conf = dir + sep + "fonts.conf";
std::ofstream cf(conf, std::ios::trunc);
if (cf) {
cf << "<?xml version=\"1.0\"?>\n"
      "<!DOCTYPE fontconfig SYSTEM \"fonts.dtd\">\n"
      "<fontconfig>\n"
      "  <dir>" << dir << "</dir>\n"
      "  <cachedir>" << dir << "/cache</cachedir>\n"
      "  <config></config>\n"
      "</fontconfig>\n";
cf.close();
#ifndef _WIN32
// Do not clobber an operator-set FONTCONFIG_*; only fill when unset.
if (!std::getenv("FONTCONFIG_FILE")) {
setenv("FONTCONFIG_FILE", conf.c_str(), 0);
}
if (!std::getenv("FONTCONFIG_PATH")) {
setenv("FONTCONFIG_PATH", dir.c_str(), 0);
}
#endif
}
}

if (all_ok) {
done = true;
}
}

} // namespace duckdb
''')
    print(f"wrote {out_path} ({out_path.stat().st_size} bytes, {len(blobs)} fonts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
