#!/usr/bin/env python3
"""Generate src/base14_font_data.cpp from third_party/fonts/*.otf.

Community-extensions ship a single .duckdb_extension binary with no companion
data files, so base-14 substitute fonts must be compiled into the extension
and extracted to a temp directory at runtime for poppler's path-based
GlobalParams::addFontFile API.

Usage:
  python3 scripts/embed_base14_fonts.py third_party/fonts path/to/base14_font_data.cpp
"""

from __future__ import annotations

import sys
from pathlib import Path

# PDF base-14 name -> URW OTF filename (Artifex urw-base35-fonts 20200910)
BASE14 = [
    ("Helvetica", "NimbusSans-Regular.otf"),
    ("Helvetica-Bold", "NimbusSans-Bold.otf"),
    ("Helvetica-Oblique", "NimbusSans-Italic.otf"),
    ("Helvetica-BoldOblique", "NimbusSans-BoldItalic.otf"),
    ("Times-Roman", "NimbusRoman-Regular.otf"),
    ("Times-Bold", "NimbusRoman-Bold.otf"),
    ("Times-Italic", "NimbusRoman-Italic.otf"),
    ("Times-BoldItalic", "NimbusRoman-BoldItalic.otf"),
    ("Courier", "NimbusMonoPS-Regular.otf"),
    ("Courier-Bold", "NimbusMonoPS-Bold.otf"),
    ("Courier-Oblique", "NimbusMonoPS-Italic.otf"),
    ("Courier-BoldOblique", "NimbusMonoPS-BoldItalic.otf"),
    ("Symbol", "StandardSymbolsPS.otf"),
    ("ZapfDingbats", "D050000L.otf"),
]


def c_ident(filename: str) -> str:
    return "kFont_" + filename.replace("-", "_").replace(".", "_")


def emit_array(out, name: str, data: bytes) -> None:
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        line = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + 16 < len(data):
            out.write(f"\t{line},\n")
        else:
            out.write(f"\t{line}\n")
    out.write("};\n")
    out.write(f"static const size_t {name}_len = {len(data)};\n\n")


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    font_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    if not font_dir.is_dir():
        print(f"font dir not found: {font_dir}", file=sys.stderr)
        return 1

    blobs = []
    for base14_name, filename in BASE14:
        path = font_dir / filename
        if not path.is_file():
            print(f"missing font file: {path}", file=sys.stderr)
            return 1
        blobs.append((base14_name, filename, path.read_bytes()))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("// AUTO-GENERATED by scripts/embed_base14_fonts.py — do not edit.\n")
        out.write("// Source fonts: third_party/fonts/ (URW++ base35, tag 20200910).\n\n")
        out.write('#include "base14_fonts.hpp"\n\n')
        out.write("#include \"GlobalParams.h\"\n\n")
        out.write("#include <cerrno>\n")
        out.write("#include <cstdio>\n")
        out.write("#include <cstdlib>\n")
        out.write("#include <cstring>\n")
        out.write("#include <fstream>\n")
        out.write("#include <string>\n\n")
        out.write("#ifdef _WIN32\n")
        out.write("#include <direct.h>\n")
        out.write("#include <io.h>\n")
        out.write("#else\n")
        out.write("#include <sys/stat.h>\n")
        out.write("#include <sys/types.h>\n")
        out.write("#include <unistd.h>\n")
        out.write("#endif\n\n")

        for base14_name, filename, data in blobs:
            emit_array(out, c_ident(filename), data)

        out.write("struct Base14FontBlob {\n")
        out.write("\tconst char *base14_name;\n")
        out.write("\tconst char *filename;\n")
        out.write("\tconst unsigned char *data;\n")
        out.write("\tsize_t size;\n")
        out.write("};\n\n")
        out.write("static const Base14FontBlob kBase14Fonts[] = {\n")
        for base14_name, filename, _data in blobs:
            ident = c_ident(filename)
            out.write(f'\t{{"{base14_name}", "{filename}", {ident}, {ident}_len}},\n')
        out.write("};\n")
        out.write(f"static const size_t kBase14FontCount = {len(blobs)};\n\n")

        out.write(r'''
static std::string Base14TempRoot() {
#ifdef _WIN32
	const char *candidates[] = {std::getenv("TEMP"), std::getenv("TMP"), "."};
#else
	const char *candidates[] = {std::getenv("TMPDIR"), std::getenv("TMP"), "/tmp"};
#endif
	for (const char *c : candidates) {
		if (c && *c) {
			std::string dir(c);
			while (dir.size() > 1 && (dir.back() == '/' || dir.back() == '\\')) {
				dir.pop_back();
			}
			return dir;
		}
	}
	return ".";
}

static bool EnsureDir(const std::string &path) {
#ifdef _WIN32
	if (_mkdir(path.c_str()) == 0) {
		return true;
	}
	return errno == EEXIST;
#else
	if (mkdir(path.c_str(), 0700) == 0) {
		return true;
	}
	return errno == EEXIST;
#endif
}

static bool WriteFileIfNeeded(const std::string &path, const unsigned char *data, size_t size) {
	// Reuse an existing file only when the size matches (cheap integrity check).
	{
		std::ifstream in(path, std::ios::binary | std::ios::ate);
		if (in && static_cast<size_t>(in.tellg()) == size) {
			return true;
		}
	}
	const std::string tmp = path + ".tmp";
	{
		std::ofstream out(tmp, std::ios::binary | std::ios::trunc);
		if (!out) {
			return false;
		}
		out.write(reinterpret_cast<const char *>(data), static_cast<std::streamsize>(size));
		if (!out) {
			return false;
		}
	}
#ifdef _WIN32
	_unlink(path.c_str());
	if (rename(tmp.c_str(), path.c_str()) != 0) {
		_unlink(tmp.c_str());
		return false;
	}
#else
	if (rename(tmp.c_str(), path.c_str()) != 0) {
		std::remove(tmp.c_str());
		return false;
	}
#endif
	return true;
}

namespace duckdb {

// Extract bundled URW base-14 OTFs to a process temp dir and register them with
// poppler's GlobalParams so GfxFont::locateFont resolves Helvetica/etc. via
// findFontFile *before* fontconfig / system font search. Safe to call under
// PopplerMutex; idempotent.
void EnsurePdfBase14Fonts() {
	static bool done = false;
	if (done) {
		return;
	}
	// poppler creates globalParams on first document open; without it we cannot
	// register fonts yet. Caller retries on the next render.
	if (!globalParams) {
		return;
	}

#ifdef _WIN32
	const char sep = '\\';
#else
	const char sep = '/';
#endif
	const std::string dir = Base14TempRoot() + sep + "duckdb_pdf_base14_fonts_v1";
	if (!EnsureDir(dir)) {
		// Non-fatal: leave done=false so a later call can retry; poppler may
		// still find system fonts, and the fail-loudly path remains as a last resort.
		return;
	}

	bool all_ok = true;
	for (size_t i = 0; i < kBase14FontCount; i++) {
		const Base14FontBlob &blob = kBase14Fonts[i];
		const std::string path = dir + sep + blob.filename;
		if (!WriteFileIfNeeded(path, blob.data, blob.size)) {
			all_ok = false;
			continue;
		}
		// Register under the canonical PDF base-14 name. GfxFont::locateFont
		// checks globalParams->findFontFile(name) first, so this works with and
		// without WITH_FONTCONFIGURATION_FONTCONFIG (where setupBaseFonts is a
		// no-op and findBase14FontFile goes through fontconfig).
		globalParams->addFontFile(std::string(blob.base14_name), path);
	}
	// Also point setupBaseFonts at our dir for non-fontconfig poppler builds
	// that still walk their displayFontTab (they look for legacy n0*.pfb names
	// and will skip names we already registered above).
	globalParams->setupBaseFonts(dir.c_str());

	if (all_ok) {
		done = true;
	}
}

} // namespace duckdb
''')
    print(f"wrote {out_path} ({out_path.stat().st_size} bytes, {len(blobs)} fonts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
