#!/usr/bin/env python3
"""Generate tessdata_embed.cpp from third_party/tessdata/*.traineddata.

Community-extensions ship a single .duckdb_extension with no companion data
files. Tesseract still needs <lang>.traineddata on disk for TessBaseAPI::Init.
We compile eng (tessdata_fast) into the binary and extract it to a process
temp dir on first OCR so English OCR works with zero host tessdata install.

Usage:
  python3 scripts/embed_tessdata.py third_party/tessdata path/to/tessdata_embed.cpp
"""

from __future__ import annotations

import sys
from pathlib import Path

# language code -> filename under third_party/tessdata/
BUNDLED = [
    ("eng", "eng.traineddata"),
]


def c_ident(filename: str) -> str:
    return "kTess_" + filename.replace("-", "_").replace(".", "_")


def emit_array(out, name: str, data: bytes) -> None:
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        line = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + 16 < len(data):
            out.write(f"\t{line},\n")
        else:
            out.write(f"\t{line}\n")
    out.write("};\n")
    out.write(f"static const size_t {name}_len = {len(data)};\n\n")


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    data_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    if not data_dir.is_dir():
        print(f"tessdata dir not found: {data_dir}", file=sys.stderr)
        return 1

    blobs = []
    for lang, filename in BUNDLED:
        path = data_dir / filename
        if not path.is_file():
            print(f"missing model file: {path}", file=sys.stderr)
            return 1
        blobs.append((lang, filename, path.read_bytes()))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("// AUTO-GENERATED by scripts/embed_tessdata.py — do not edit.\n")
        out.write("// Source: third_party/tessdata/ (tessdata_fast eng, Apache-2.0).\n")
        out.write("// Declares pdf_ocr::EnsureBundledTessdataDir / HasBundledTessdata\n")
        out.write("// (see ocr_ops.hpp). No extension headers — keeps this TU isolatable.\n\n")
        out.write("#include <cerrno>\n")
        out.write("#include <cstdio>\n")
        out.write("#include <cstdlib>\n")
        out.write("#include <cstring>\n")
        out.write("#include <fstream>\n")
        out.write("#include <string>\n\n")
        out.write("#ifdef _WIN32\n")
        out.write("#include <direct.h>\n")
        out.write("#include <io.h>\n")
        out.write("#else\n")
        out.write("#include <sys/stat.h>\n")
        out.write("#include <sys/types.h>\n")
        out.write("#include <unistd.h>\n")
        out.write("#endif\n\n")

        for lang, filename, data in blobs:
            emit_array(out, c_ident(filename), data)

        out.write("struct BundledTessModel {\n")
        out.write("\tconst char *language;\n")
        out.write("\tconst char *filename;\n")
        out.write("\tconst unsigned char *data;\n")
        out.write("\tsize_t size;\n")
        out.write("};\n\n")
        out.write("static const BundledTessModel kBundledTessModels[] = {\n")
        for lang, filename, _data in blobs:
            ident = c_ident(filename)
            out.write(f'\t{{"{lang}", "{filename}", {ident}, {ident}_len}},\n')
        out.write("};\n")
        out.write(f"static const size_t kBundledTessModelCount = {len(blobs)};\n\n")

        out.write(
            r'''
static std::string TessTempRoot() {
#ifdef _WIN32
const char *candidates[] = {std::getenv("TEMP"), std::getenv("TMP"), "."};
#else
const char *candidates[] = {std::getenv("TMPDIR"), std::getenv("TMP"), "/tmp"};
#endif
for (const char *c : candidates) {
if (c && *c) {
std::string dir(c);
while (dir.size() > 1 && (dir.back() == '/' || dir.back() == '\\')) {
dir.pop_back();
}
return dir;
}
}
return ".";
}

static bool EnsureDir(const std::string &path) {
#ifdef _WIN32
if (_mkdir(path.c_str()) == 0) {
return true;
}
return errno == EEXIST;
#else
if (mkdir(path.c_str(), 0755) == 0) {
return true;
}
return errno == EEXIST;
#endif
}

static bool WriteFileIfNeeded(const std::string &path, const unsigned char *data, size_t size) {
{
std::ifstream in(path, std::ios::binary | std::ios::ate);
if (in && static_cast<size_t>(in.tellg()) == size) {
return true;
}
}
const std::string tmp = path + ".tmp";
{
std::ofstream out(tmp, std::ios::binary | std::ios::trunc);
if (!out) {
return false;
}
out.write(reinterpret_cast<const char *>(data), static_cast<std::streamsize>(size));
if (!out) {
return false;
}
}
#ifdef _WIN32
_unlink(path.c_str());
if (rename(tmp.c_str(), path.c_str()) != 0) {
_unlink(tmp.c_str());
return false;
}
#else
if (rename(tmp.c_str(), path.c_str()) != 0) {
std::remove(tmp.c_str());
return false;
}
#endif
return true;
}

namespace pdf_ocr {

// Extract bundled language models (currently eng from tessdata_fast) into a
// process temp dir. Returns the directory TessBaseAPI::Init should receive, or
// empty if the language is not bundled / extract failed.
// Idempotent. No duckdb / poppler / tesseract headers.
std::string EnsureBundledTessdataDir(const std::string &language) {
if (language.empty()) {
return std::string();
}
const BundledTessModel *hit = nullptr;
for (size_t i = 0; i < kBundledTessModelCount; i++) {
if (language == kBundledTessModels[i].language) {
hit = &kBundledTessModels[i];
break;
}
}
if (!hit) {
return std::string();
}

#ifdef _WIN32
const char sep = '\\';
#else
const char sep = '/';
#endif
// Bump suffix when payload changes so stale partial extracts are not reused.
const std::string dir = TessTempRoot() + sep + "duckdb_pdf_tessdata_v1_fast";
if (!EnsureDir(dir)) {
return std::string();
}
const std::string path = dir + sep + hit->filename;
if (!WriteFileIfNeeded(path, hit->data, hit->size)) {
return std::string();
}
return dir;
}

bool HasBundledTessdata(const std::string &language) {
for (size_t i = 0; i < kBundledTessModelCount; i++) {
if (language == kBundledTessModels[i].language) {
return true;
}
}
return false;
}

} // namespace pdf_ocr
'''
        )

    total = sum(len(d) for _, _, d in blobs)
    print(f"wrote {out_path} ({out_path.stat().st_size} bytes, {len(blobs)} models, {total} payload bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
